Updated readme information to describe current project
NerdyNomads/COMP4350-Project pull request #27
Opened 2022-02-09 23:46 UTC by OfficialArms

The project has been changed from a travel planner to a chrome extension for saving blocks of text. These changes will update our readme documentation to reflect this change.

2022-02-09 23:58 UTC, mariellemanlulu requested changes

2022-02-09 23:58 UTC, mariellemanlulu commented on readme.md
> +# COMP 4350 - Nerdy Nomads
Should we add our course section ???

Also, eventually, we would have to change the title to our project name after we decide.

2022-02-09 23:58 UTC, mariellemanlulu commented on readme.md
> +| Faith de Leon  | deleonkf  | deleonkf@myumanitoba.ca
Should we add links to GitHub username?

2022-02-11 23:30 UTC, r3ym3l commented on readme.md
> +- Share workspaces with other users
- Access web page from browser extension panel

2022-02-13 20:15 UTC, mariellemanlulu approved these changes

2022-02-13 20:41 UTC, merged